import {
  User,
  Users,
  FolderOpen,
  Package,
  Building,
  TrendingUp,
  ChartNoAxesCombined,
  ShieldX,
  Calendar,
  MapPinned,
  BarChart3,
  UserRoundPlus,
  Home,
  Clock,
  Banknote,
  Truck,
  Layers,
  Settings,
  LayoutGrid,
  Briefcase,
  UserCheck,
  Network,
  PieChart,
  KanbanSquare,
  BookOpen,
  Plane,
  Star,
  FileWarning,
  AlertTriangle,
  HardHat,
} from "lucide-react";
import { Roles } from "@/lib/roles";

// Categorías de módulos
export const moduleCategories = [
  // ── Administrador ────────────────────────────────────────────────────────────
  {
    id: "administrador",
    title: "Administrador",
    icon: Home,
    modules: [
      {
        id: 900,
        name: "Inicio",
        path: "/dashboard/administrador/inicio",
        icon: Home,
        roles: [Roles.ADMINISTRADOR],
      },
    ],
  },
  // ── Proyectos ────────────────────────────────────────────────────────────────
  {
    id: "proyectos",
    title: "Proyectos",
    icon: FolderOpen,
    modules: [
      {
        id: 2,
        name: "Clientes",
        path: "/dashboard/proyectos/clientes",
        icon: Users,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 3,
        name: "Proyectos",
        path: "/dashboard/proyectos/proyectos",
        icon: Building,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 4,
        name: "Proyectos Cerrados",
        path: "/dashboard/proyectos/proyectos-cerrados",
        icon: Building,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 5,
        name: "Mapa de Proyectos",
        path: "/dashboard/proyectos/mapa",
        icon: MapPinned,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 6,
        name: "Seguimiento Cotizaciones",
        path: "/dashboard/proyectos/seguimiento-cotizaciones",
        icon: FolderOpen,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 7,
        name: "Proyecciones",
        path: "/dashboard/proyectos/proyecciones",
        icon: TrendingUp,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 8,
        name: "Resumen Proyección",
        path: "/dashboard/proyectos/resumen-proyeccion",
        icon: ChartNoAxesCombined,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 9,
        name: "Auditoria Proyectos",
        path: "/dashboard/proyectos/auditoria-proyectos",
        icon: ShieldX,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 10,
        name: "Asesoría Técnica",
        path: "/dashboard/proyectos/asesoria-tecnica",
        icon: FolderOpen,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
    ],
  },
  // ── Estructurales ────────────────────────────────────────────────────────────
  {
    id: "estructurales",
    title: "Estructurales",
    icon: Layers,
    modules: [
      {
        id: 31,
        name: "Staff",
        path: "/dashboard/estructurales/staff-estructurales",
        icon: UserRoundPlus,
        roles: [Roles.ADMINISTRADOR, Roles.ESTRUCTURAL],
      },
      {
        id: 32,
        name: "Oficina Estructural",
        path: "/dashboard/estructurales/oficina-estructural",
        icon: Building,
        roles: [Roles.ADMINISTRADOR, Roles.ESTRUCTURAL],
      },
      {
        id: 33,
        name: "Seguimiento Estructural",
        path: "/dashboard/proyectos/seguimiento-estructural",
        icon: FolderOpen,
        roles: [Roles.ADMINISTRADOR, Roles.ESTRUCTURAL, Roles.COMERCIAL],
      },
    ],
  },
  // ── Despachos ────────────────────────────────────────────────────────────────
  {
    id: "despachos",
    title: "Despachos",
    icon: Truck,
    modules: [
      {
        id: 50,
        name: "Productos",
        path: "/dashboard/despachos/productos",
        icon: Package,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 51,
        name: "Despachos",
        path: "/dashboard/despachos/despachos",
        icon: Calendar,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL, Roles.INGENIERO],
      },
    ],
  },
  // ── Analítica ────────────────────────────────────────────────────────────────
  {
    id: "analitica",
    title: "Analítica",
    icon: TrendingUp,
    modules: [
      {
        id: 100,
        name: "Comisiones Comercial",
        path: "/dashboard/analitica/comisiones-comercial",
        icon: User,
        roles: [Roles.ADMINISTRADOR, Roles.COMERCIAL],
      },
      {
        id: 101,
        name: "Seguimiento Cotizaciones",
        path: "/dashboard/analitica/seguimiento-cotizaciones",
        icon: BarChart3,
        roles: [Roles.ADMINISTRADOR],
      },
    ],
  },
  // ── Odoo ─────────────────────────────────────────────────────────────────────
  {
    id: "odoo",
    title: "Odoo",
    icon: Layers,
    modules: [
      {
        id: 301,
        name: "OC y Recepciones",
        path: "/dashboard/odoo/oc-recepciones",
        icon: FolderOpen,
        roles: [Roles.ADMINISTRADOR],
      },
      {
        id: 302,
        name: "Seguimiento de OC",
        path: "/dashboard/odoo/seguimiento-oc",
        icon: FolderOpen,
        roles: [Roles.ADMINISTRADOR],
      },
    ],
  },
  // ── Recursos Humanos ─────────────────────────────────────────────────────────
  {
    id: "recursos-humanos",
    title: "Recursos Humanos",
    icon: Users,
    modules: [
      {
        id: 60,
        name: "Inicio",
        path: "/dashboard/recursos-humanos/inicio",
        icon: Home,
        roles: [Roles.RECURSOS_HUMANOS],
      },
      {
        id: 61,
        name: "Asistencia",
        path: "/dashboard/recursos-humanos/asistencia",
        icon: Clock,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
      {
        id: 62,
        name: "Nóminas",
        path: "/dashboard/recursos-humanos/nominas",
        icon: Banknote,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
      {
        id: 63,
        name: "Personal",
        path: "/dashboard/recursos-humanos/personal",
        icon: Users,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
      {
        id: 64,
        name: "Vigentes",
        path: "/dashboard/recursos-humanos/vigentes",
        icon: UserCheck,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
      {
        id: 65,
        name: "Organigrama",
        path: "/dashboard/recursos-humanos/organigrama",
        icon: Network,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
      {
        id: 66,
        name: "KPIs & Reportes",
        path: "/dashboard/recursos-humanos/reportes",
        icon: PieChart,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
      {
        id: 67,
        name: "Reclutamiento",
        path: "/dashboard/recursos-humanos/reclutamiento",
        icon: KanbanSquare,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
      {
        id: 68,
        name: "Capacitaciones",
        path: "/dashboard/recursos-humanos/capacitaciones",
        icon: BookOpen,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
      {
        id: 69,
        name: "Vacaciones & Permisos",
        path: "/dashboard/recursos-humanos/vacaciones",
        icon: Plane,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
      {
        id: 70,
        name: "Evaluaciones",
        path: "/dashboard/recursos-humanos/evaluaciones",
        icon: Star,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
      },
    ],
  },
  // ── Oficina Técnica ──────────────────────────────────────────────────────────
  {
    id: "oficina-tecnica",
    title: "Oficina Técnica",
    icon: FileWarning,
    modules: [
        {
        id: 400,
        name: "Inicio",
        path: "/dashboard/oficina-tecnica/inicio",
        icon: Home,
        roles: [Roles.OFICINA_TECNICA],
        },
        {
        id: 401,
        name: "Errores en Planos",
        path: "/dashboard/oficina-tecnica/errores-planos",
        icon: AlertTriangle,
        roles: [Roles.OFICINA_TECNICA],
        },
    ],
  },
  // ── Planta ───────────────────────────────────────────────────────────────────
  {
    id: "planta",
    title: "Planta",
    icon: HardHat,
    modules: [
        {
        id: 501,
        name: "Reportar Error en Plano",
        path: "/dashboard/planta/reportar-error",
        icon: AlertTriangle,
        roles: [Roles.PLANTA, Roles.ADMINISTRADOR],
        },
    ],
  },
  // ── Configuración (siempre al último) ────────────────────────────────────────
  {
    id: "configuracion-rrhh",
    title: "Configuración",
    icon: Settings,
    modules: [
        {
        id: 71,
        name: "Áreas",
        path: "/dashboard/recursos-humanos/areas",
        icon: LayoutGrid,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
        },
        {
        id: 72,
        name: "Cargos",
        path: "/dashboard/recursos-humanos/cargos",
        icon: Briefcase,
        roles: [Roles.RECURSOS_HUMANOS, Roles.ADMINISTRADOR],
        },
        {
        id: 1,
        name: "Trabajadores",
        path: "/dashboard/recursos-humanos/trabajadores",
        icon: User,
        roles: [Roles.ADMINISTRADOR],
        },
        {
        id: 73,
        name: "Configuración General",
        path: "/dashboard/configuracion/general",
        icon: Settings,
        roles: [
            Roles.RECURSOS_HUMANOS,
            Roles.ADMINISTRADOR,
            Roles.OFICINA_TECNICA,
            Roles.PLANTA,
            Roles.COMERCIAL,
            Roles.ESTRUCTURAL,
            Roles.INGENIERO,
            Roles.GERENCIA,
        ],
        },
    ],
  },
];
