export enum Roles {
  ADMINISTRADOR = "ADMINISTRADOR",
  COMERCIAL = "COMERCIAL",
  ESTRUCTURAL = "ESTRUCTURAL",
  RECURSOS_HUMANOS = "RECURSOS_HUMANOS",
  OFICINA_TECNICA = "OFICINA_TECNICA",
  PLANTA = "PLANTA",
  INGENIERO = "INGENIERO",
  GERENCIA = "GERENCIA",
}
